global:
  scrape_interval: 5s  # Coleta métricas a cada 5 segundos

scrape_configs:
  - job_name: "locust"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["monitor-service:9646"]  # Coletando métricas do Locust rodando no Docker
